name: photo_puzzle
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  audioplayers: any
  path_provider: any
  image: ^4.1.3  # ← 画像分割に必須！

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/sample.jpg
    - assets/sounds/place_success.mp3
    - assets/sounds/place_fail.mp3
    - assets/sounds/completed.mp3